### ISSUE TITLE
Is there user-visible changes in tagged-0.8.8

### ISSUE THREAD

**Issue by phadej** [ekmett/tagged#59]
I checked a diff, and there doesn't seem so, but I'm still asking to be sure.

In other words, could `tagged-0.8.8` been `tagged-0.8.7.1`? [Quoting PVP](https://pvp.haskell.org/)

> 3. Other changes. Otherwise, e.g. if change consist only of corrected documentation, non-visible change to allow different dependency range etc. A.B.C MAY remain the same (other version components may change).

**Comment by RyanGlScott** [comment]
There are no user-visible changes. There are _code_ changes in https://github.com/ekmett/tagged/commit/44fef366778f3e0cf83e78ee18640889db6a8dfc, however, and I always bump the tertiary version number after code changes as a matter of policy. The only way to guard against something with CPP is to have a change reflected in a tertiary version number or higher, and it would be a shame if you couldn't guard against a potential mistake in the new code due to the version bump not being CPP-able.

**Comment by phadej** [comment]
Good to know about policy.

For the future, could you state explicitly in the changelog that there *shouldn't be user visible changes*. E.g. `binary-instances` has a tight upper bound, because it defines an orphan instance, so the new release has a cascade effect (though in practice it shouldn't).

**Comment by RyanGlScott** [comment]
Sure, I'll keep that in mind going forward.
